### ISSUE TITLE
Amazon Prime recap skip isn't working again.

### ISSUE THREAD

**Issue by n3cr0cr0w** [naman03malhotra/auto-skip-for-netflix-and-prime#1]
This is what I wrote up to fix it for myself.

document.evaluate('//div[text()="Skip Recap"]', document, null, XPathResult.ANY_TYPE, null).iterateNext().click();

**Comment by naman03malhotra** [comment]
@n3cr0cr0w 
I released the latest update as prime changed its UI (they added CSS modules), it should work fine now, please update the extension. V2.2.0/

I have added new XPath tags for prime video.

**Comment by naman03malhotra** [comment]
Also, your prime video should be in the English language in order for this to work. For example, if you are in Spain and `Skip Intro` translates to `Presiona Intro`, it won't work. It has to be `Skip Intro`. This is due to the recent change prime did in their UI. Please change it accordingly.
