### ISSUE TITLE
Add documentation about analytics

### ISSUE THREAD

**Issue by adiac** [naman03malhotra/auto-skip-for-netflix-and-prime#3]
The code involves some kind of analytic tracking. For transparency, please state what data exactly is send and for what purpose it is used. This should also be mentioned in the README file. Thanks.

**Comment by naman03malhotra** [comment]
Thanks @adiac, I'll update the info in the master branch asap

**Comment by naman03malhotra** [comment]
@adiac I have added the same in README. Thank you for pointing that out.
